#!/bin/bash

sudo cp '/home/pi/wkspc/rpi-peripheral/server/services/sysinfo/characteristics/rcConfig' '/etc/rc.local'

# cd /etc
# readPath='/home/pi/wkspc/rpi-peripheral/server/services/sysinfo/characteristics/rcConfig'

# >rc.local
# while IFS= read -r line
# do
# 	echo "$line" >> rc.local
# done <"$readPath"
